import { ComponentInstance, WireSegment } from '../types';
import { COMPONENT_LIBRARY, GRID_SIZE } from '../constants';

// A simple Union-Find implementation
class UnionFind {
  parent: Record<string, string>;
  constructor() {
    this.parent = {};
  }
  
  find(i: string): string {
    if (this.parent[i] === undefined) {
      this.parent[i] = i;
    }
    if (this.parent[i] !== i) {
      this.parent[i] = this.find(this.parent[i]);
    }
    return this.parent[i];
  }
  
  union(i: string, j: string) {
    const rootI = this.find(i);
    const rootJ = this.find(j);
    if (rootI !== rootJ) {
      this.parent[rootI] = rootJ;
    }
  }
}

export const generateNetlist = (components: ComponentInstance[], wires: WireSegment[]) => {
  const uf = new UnionFind();
  const nodes = new Set<string>();
  
  // Helper to generate a spatial key for a point
  const locKey = (x: number, y: number) => `${Math.round(x)},${Math.round(y)}`;

  // 1. Process Wires
  // Connect all points within a single wire
  wires.forEach(wire => {
    for (let i = 0; i < wire.points.length - 2; i += 2) {
      const p1 = locKey(wire.points[i], wire.points[i+1]);
      const p2 = locKey(wire.points[i+2], wire.points[i+3]);
      uf.union(p1, p2);
      nodes.add(p1);
      nodes.add(p2);
    }
  });

  // 2. Process Component Pins
  // Map component pins to spatial locations
  const componentPinNets: Record<string, Record<string, string>> = {}; // compId -> { pinId: spatialKey }

  components.forEach(comp => {
    const def = COMPONENT_LIBRARY[comp.type];
    if (!def) return;
    
    // Calculate absolute pin positions based on rotation
    // This is a simplified rotation logic (center of rotation usually 0,0 of component)
    // In our defs, pins are relative to component x,y.
    
    // We need to rotate the pin offset.
    const rad = (comp.rotation * Math.PI) / 180;
    const cos = Math.cos(rad);
    const sin = Math.sin(rad);
    
    // Find center of component to rotate around? 
    // Usually EDA tools rotate around the origin of the component (0,0 relative).
    // Our components have width/height. Let's assume 0,0 is top-left anchor.
    // For better UX, rotation usually happens around center.
    // But to keep it simple, we rotate relative point (px, py) around (0,0) then add (comp.x, comp.y).
    
    componentPinNets[comp.id] = {};

    def.pins.forEach(pin => {
      // Rotate pin relative to (0,0)
      // If width/height are involved, often we rotate around center (w/2, h/2).
      // Let's stick to 0,0 anchor rotation for simplicity or center if easy.
      // Let's use center.
      const cx = def.width / 2;
      const cy = def.height / 2;
      
      const dx = pin.x - cx;
      const dy = pin.y - cy;
      
      const rx = dx * cos - dy * sin;
      const ry = dx * sin + dy * cos;
      
      const finalX = comp.x + cx + rx;
      const finalY = comp.y + cy + ry;

      // Snap calculated pin pos to grid to ensure matching with wires
      const key = locKey(Math.round(finalX / GRID_SIZE) * GRID_SIZE, Math.round(finalY / GRID_SIZE) * GRID_SIZE);
      
      uf.union(key, key); // Ensure it exists
      componentPinNets[comp.id][pin.id] = key;
    });
  });

  // 3. Assign Net Names
  const rootToNetName: Record<string, string> = {};
  let netCounter = 1;

  // Identify GND
  // If we had a specific GND component, we would find its pin and force that net to '0'
  
  // Create mapping
  Object.keys(uf.parent).forEach(node => {
    const root = uf.find(node);
    if (!rootToNetName[root]) {
      // Check if any GND component is connected to this root
      const isGnd = components.some(c => {
        if (c.type === 'gnd') {
             const pinKey = componentPinNets[c.id]['1'];
             return uf.find(pinKey) === root;
        }
        return false;
      });

      if (isGnd) {
        rootToNetName[root] = '0';
      } else {
        rootToNetName[root] = `N${String(netCounter).padStart(3, '0')}`;
        netCounter++;
      }
    }
  });

  // 4. Generate Lines
  const lines: string[] = [];
  const title = `* Generated by Web Schematic Editor on ${new Date().toISOString()}`;
  lines.push(title);

  components.forEach(comp => {
    if (comp.type === 'gnd') return; // Don't output GND components as devices
    
    const def = COMPONENT_LIBRARY[comp.type];
    let line = def.template; // e.g., "R{{name}} {{1}} {{2}} {{value}}"
    
    // Replace pins
    def.pins.forEach(pin => {
      const pinKey = componentPinNets[comp.id][pin.id];
      const root = uf.find(pinKey);
      const netName = rootToNetName[root] || 'FLOAT';
      line = line.replace(`{{${pin.id}}}`, netName);
    });
    
    // Replace properties
    Object.entries(comp.properties).forEach(([key, val]) => {
      line = line.replace(`{{${key}}}`, val);
    });

    lines.push(line);
  });

  lines.push(".END");
  return lines.join('\n');
};